let study = {
  id: 0,
  consortium: 'STRING',
  grant: 'STRING',
  isConsortiumAnalysis: 'STRING',
  isModelSystem: 'STRING',
  species: 'STRING',
  study: 'STRING',
  dataType: 'STRING',
  dataSubtype: 'STRING',    
  analysisType: 'STRING',
  assay: 'STRING',
  assayTarget: 'STRING',
  organ: 'STRING',
  tissue: 'STRING',
  cellType: 'STRING',
  isMultiSpecimen: 'STRING',
  fileFormat: 'STRING',
  name: 'STRING',
  group: 'STRING',
  specimenIdSource: 'STRING',
  specimenID: 'STRING',
  createdOn: 'STRING',
  createdBy: 'STRING',
  etag: 'STRING',
  type: 'STRING',
  currentVersion: 0,
  parentId: 'STRING',
  benefactorId: 'STRING',
  projectId: 'STRING',
  modifiedOn: 'DATE',
  modifiedBy: 'USERID',
  dataFileHandleId: 'STRING'
}
export default study;
